name: release

on: 
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "The tag to release"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_REF: ${{ github.event_name == 'push' && github.ref_name || inputs.tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.RELEASE_REF }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
