name: tests

on: 
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"
    
    steps: 
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: install staticcheck
        run: |
          cd /tmp && go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Install gosec
        run: |
          cd /tmp && go install github.com/securego/gosec/v2/cmd/gosec@2.20.0

      - name: Make tests
        run: |
          make
